### ISSUE TITLE
Select A Particular Point for Snapshot?

### ISSUE THREAD

**Issue by dano2** [sebible/cordova-videosnapshot#5]
Hi. Thanks for the plugin! Can this be "rigged" to select a particular time/frame for the snapshot, instead of taking random shots? For example, the following works beautifully, but sadly won't work on an Android browser.

http://www.html5multimedia.com/code/ch9/video-canvas-screenshot.html

**Comment by ledzep2** [comment]
Hi. I went through the same thing trying out the browser method n found it was either inconsistent or slow on Android n IOS. That's why I decided to implement it in native plugins. 

And to your question, it can! If you feed it with a count of ((duration / desired_time) - 1) where desired_time must be larger than 1 second, you will get an array of snapshots with the desired shot at index 0. The price of this is that you will get some unwanted shots (waste of cpu n space) and even a lot of them if you have a relatively small desired_time.

A better way is to fork n modify it to satisfy ur needs.

**Comment by dano2** [comment]
Hi zep. I just got your plugin installed and working, and it is VERY cool!
I think I could better understand your strategy for screen shooting at a particular point with an example.
So, if I have a video that is 3 minutes long. And I want a screenshot at 15.479 seconds, what exactly should my settings below look like?

Note that I'm getting the desired time position from video.currentTime which is in decimal seconds.	

        var duration = ?;
	var desired_time = ?;
	var theCount = ((duration / desired_time) - 1);

	var options = {
	    source: "file:///mnt/sdcard/DCIM/Camera/0.mp4",
	    count: theCount,
	    timeStamp: true
	}

Thanks.

**Comment by ledzep2** [comment]
In this case, duration will be 180 and desired_time will be floor of 15.479.  And you will get a bunch of snapshots with the first one at 15.000 seconds. Note that you might only be able to get a snapshot at a integer time by which the duration is divisible. And you need to get duration of the video in some other way, ex. from an html5 video plugin https://github.com/amuelli/Html5Video/blob/d22236b0f4d4cf053c740553758ef0f572acfba0/README.md] 

I have to say, it is a lot simpler to fork n modify the native code to get this done.

**Comment by dano2** [comment]
Ok. I couldn't get this to work for me how I was hoping. I'll poke around for some tutorials on how to create a phonegap plugin. Do you have a particular source that you'd recommend? I'm primarily a php developer. But I think I could hack together some java. ObjC is another question.

**Comment by ledzep2** [comment]
Sorry for not being able to help. Good luck~
